# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Business Jekyll Them 2e
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://galacticsearch.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Galacticsearch
address_line: Via Ludovisi 39-45, Rome, 54267, Italy
telephone_number: 1.800.245.356
fax_number: 1.800.245.357
company_email: hello@galacticsearch.io
google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d828.2021830739803!2d-58.41357944548722!3d-33.86881983306112!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2suy!4v1706466768164!5m2!1ses!2suy

# Social Link
tiktok_link: https://www.tiktok.com/@galacticsearch
twitter_link: https://twitter.com/galactic_search
linkedin_link: https://www.linkedin.com/company/galacticsearch/
instagram_link: https://www.instagram.com/galactic_search/
medium_link: https://medium.com/@nicomoraes
github_link: https://github.com/galacticsearch

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
